name: ##PROJECT##
recipe: wordpress
config:
  webroot: web
  php: '7.4'
  xdebug: "debug,develop"
  composer_version: '2.0.6'
  via: nginx
  database: mariadb
services:
  appserver:
    build_as_root:
      - sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml
      - sed -i 's/<\/policymap>/  <policy domain="coder" rights="read|write" pattern="LABEL" \/>\n<\/policymap>/g' /etc/ImageMagick-6/policy.xml
    config:
      php: config/php.ini
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
